/** @format */

import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { sanityClient, urlFor } from '../sanity';
import { Collection } from '../typings';

interface Props {
  collections: Collection[];
}

const Home = ({ collections }: Props) => {
  console.log(collections);
  return (
    <div className='mx-auto flex min-h-screen max-w-7xl flex-col py-20 px-10'>
      <Head>
        <title>NFT Drop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='w-fit cursor-pointer text-4xl font-extralight mb-10'>
        THE <span className='font-extrabold decoration-pink-600/50 underline'>HAOHAO</span> NFT
        Market Place
      </h1>
      <div className='bg-slate-100 p-10 shadow-xl'>
        <div className='grid space-x-3 grid-cols-4 lg:grid-cols-2 md:!grid-cols-1'>
          {collections.map(collection => (
            <Link href={`/nft/${collection.slug.current}`} key={collection._id} passHref>
              <div className='flex cursor-pointer flex-col items-center transition-all duration-200 hover:scale-105'>
                <div className='relative h-96 w-80 rounded-2xl'>
                  <Image
                    src={urlFor(collection.mainImage).url()}
                    alt='mainImage'
                    objectFit='contain'
                    layout='fill'
                    className='rounded-2xl'
                  />
                </div>
                <div className=''>
                  <h2 className='text-3xl font-bold text-red-300'>{collection.title}</h2>
                  <p className='ml-2 text-sm text-gray-400'>{collection.description}</p>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const query = `*[_type == "collection"] {
  _id,
  title,
  address,
  description,
  nftCollectionName,
  mainImage {
    asset
  },
  previewImage {
    asset
  },
  slug{
    current
  },
  creator-> {
    _id,
    name,
    address,
    slug {
      current
    }
  }
}`;
  const collections = await sanityClient.fetch(query);

  return {
    props: {
      collections,
    },
  };
};
